from django.db import migrations

WORDS = [
    ("PIL", "Uzyn holtumly we iki sany uzyn gyýakly äpet haýwan", "easy"),
    ("ŽIRAF", "uzyn boýunly we uzyn aýakly haýwan", "easy"),
    ("HAMELEON", "reňkini üýtgedýän jandar", "hard"),
    ("FRANSIÝA", "Eiffel minarasy bolan şäher", "easy"),
    ("BRAZILIÝA", "Günorta Amerikada iň uly ýurt", "easy"),
    ("AWSTRALIÝA", "kenguru bolan uly kontinent", "medium"),
    ("ŞWEÝSARIÝA", "Alp daglarynyň şokoladly ýurdy", "hard"),
    ("SPAGETTI", "inçe uzyn italýan makaron görnüşi", "medium"),
    ("CAPPUCCINO", "Italýan süýtli kofesi", "hard"),
    ("NOWRUZ", "21-22-nji mart", "medium"),
    ("AFINA", "Gadymy grek mifologiýasynda Akyp paýhasyň zenan hudaýy", "medium"),
    ("AGYL", "Mal saklamak üçin çöp-çalamdan, agaçdan we beýleki zatlardan edilýän aýmança, töwerekleýin gurulýan germew.", "medium"),
    ("AJÖZE", "Hiç zat iýip-içmän, aç garna, açlygyna.", "medium"),
    ("AKGAÝYR", "Derýanyň suwunyň çekilen ýeri.", "medium"),
    ("AKYDA", "Ynanç, pikir", "medium"),
    ("ANTARKTIKA", "Dünýäniň iň uly çöli", "medium"),
    ("ARAÇA", "... taýak deger.", "medium"),
    ("GELINBARMAK", "Üzümiň görnüşi", "medium"),
    ("DA VINCI", "Mona Lisa suratyny çeken hudožnik.", "medium"),
    ("DOŇUZ", "Il aglak bolsa .... depä çykar.", "medium"),
    ("DERWEZE", "Güýçli ody bolan etrap", "medium"),
    ("GYRAT", "Göroglynyň meşhur ulag serişdesi", "medium"),
    ("INFLÝASIÝA", "Bahalaryň galmagy we pulyň hümmetiniň gaçmagy", "medium"),
    ("KÖÝTENDAG", "Äpet aýagyzlar bolan ýer", "medium"),
    ("KRIPTOWALÝUTA", "Bitcoin", "medium"),
    ("MAPBAK", "Ýapbak, ... , Topbak we Japbak", "medium"),
    ("OTTAWA", "Kanadanyň paýtagty", "medium"),
    ("PSIHOLOGIÝA", "adamlaryň özüni alyp barşy barada ylym", "medium"),
    ("SADALYKDAN", "Entek ... zyyan çeken yok", "medium"),
    ("ŞIRGAZY", "Pyragynyň Hywada okan medresesi", "medium"),
    ("TÜRKIÝE", "Hem Ýewropada hem Aziýada ýerleşýär", "medium"),
    ("ÝAMANY", "\" ..... görmedik - ýagşa nyrh bermez.\"", "medium"),
    ("AÝNANY", "... kim alsa şol alsyn, bize toý bolsa bolýar.", "medium"),
    ("BULAGAÝ", "Agzalalyk döredýän, başbozar, arabozar, bozgak.", "medium"),
    ("AÝRYBABA", "Türkmenistanyň iň beýik dag depesi", "medium"),
    ("KYÝAMAT", "Dünýäniň soňy.", "medium"),
    ("AKGA", "Maryda kaka ýa-da aga", "medium"),
    ("ALPINIST", "Daga çykmasa güni geçenok.", "medium"),
    ("ÄMMÄ", "Daşoguzda kakaň aýal dogany", "medium"),
    ("APA", "Daşoguzda eje", "medium"),
    ("BABOÇKA", "Ganatly Toyota", "medium"),
    ("BADRIN", "Lebapda hyýar", "medium"),
    ("BÖRÜK", "Maryda tahýa", "medium"),
    ("BOÝDAŞ", "Balkanda jora", "medium"),
    ("BÜRÜNÇ", "Maryda tüwi", "medium"),
    ("ÇYRAÇY", "Tehniki täzelikleri gowy görýän we satyn alýan adam.", "medium"),
    ("EJEKE", "Balkanda aýal dogan", "medium"),
    ("ERRE", "Maryda byçgy", "medium"),
    ("GUBADAG", "Fiççisinden doýup bolanok", "medium"),
    ("INSTAGRAM", "Bloggerler gowy görýär.", "medium"),
    ("LINKEDIN", "Iş, karýera we ş.m. üçin internet sahypasy", "medium"),
    ("ÖKÜZKELLE", "iri mal Toyota Camry", "medium"),
    ("OŇAT", "Maryda 'yagşy'", "medium"),
    ("TIKTOK", "Ýatmazdan öň 4 sagat seredýän", "medium"),
    ("TÜRKMENÇILIK", "Halk içinde ýöreýän jemgyýet kodeksi.", "medium"),
    ("ZERDALY", "Lebapda erik agajy we miwesi", "medium"),
    ("ŞYGYR-ŞYGYR", "ýagyş ... ýagýar", "medium"),
    ("SANTÝAGO", "Çiliniň paýtagty", "medium"),
    ("ŞYGAR", "baş pikiri, meseläni aňladýan gysga ýüzlenme", "medium"),
    ("ŞÜLE", "Ýagy azrak, suwy köpräk guýlup, tüwüden bişirilýän nahar", "medium"),
    ("ŞUM", "erbet, ýaramaz, ýaman, pis", "medium"),
    ("ŞÄNIK", "gaty gabykly, içi tohumly, maňyzly däne", "medium"),
    ("TESLA", "Elon Maskyň maşyny", "medium"),
    ("SHORTS", "YouTube-daky gysga wideolar", "medium"),
    ("YOUTUBE", "islendik zat barada wideo portal", "medium"),
    ("GMAIL", "google platformasynyň elektron bukçasy", "medium"),
    ("SWIFT", "banklaryň arasynda pul geçirme ulgamy", "medium"),
    ("RIÝAD", "Saud Arabystanyň paýtagty", "medium"),
    ("MIÇIGAN", "ABŞ-nyň iň uly kölI", "medium"),
    ("WOLGA", "Ýewropanyň iň uzyn derýasy", "medium"),
    ("GANGA", "Hindistandaky mukaddes derýa", "medium"),
    ("ARARAT", "Türkiýede iň beýik dag", "medium"),
    ("MARGIANA", "Türkmenistanda meşhur gadymy şäher", "medium"),
    ("GÖKDEPE", "\"taryhy gala\"", "medium"),
    ("TAJMAHAL", "Hindistandaky dünýä täsinligi", "medium"),
    ("PARIŽ", "Ýewropanyň söýgi şäheri", "medium"),
    ("NEW-YORK", "bu şäheriň lakamy - Uly Alma", "medium"),
    ("WIKTORIÝA", "Afrikanyň iň uly köli", "medium"),
    ("PIFAGOR", "Gadymy grek alymy (matematika)", "medium"),
    ("BARSA", "Real Madridyň garşydaşy", "medium"),
    ("BÖWREK", "Adamyň ganyny arassalaýan organ", "medium"),
    ("ARTERIÝA", "gan damary", "medium"),
    ("ERITROSIT", "Ganyň gyzyl öýjükleri", "medium"),
    ("ŞAÝAT", "Bir wakany gözi bilen gören", "medium"),
    ("ŞATYR", "Hökümdaryň, begiň, hanyň ýanyndaky hyzmatkär", "medium"),
    ("ŞAMLYK", "agşam nahar", "medium"),
    ("ŞAHANDAZ", "märekäni, saz söhbeti, oturylyşygy halaýan", "medium"),
    ("SÜZGÜÇ", "Suwuklygy arassalamak üçin ownuk gözli ýörite enjam", "medium"),
    ("UNIWERSITET", "ýokary okuw jaýy", "medium"),
    ("MÄMIŞI", "pyrtykalyň reňki", "medium"),
    ("ZÖHRE", "ýyldyzlaryň biriniň ady", "medium"),
    ("ÝALDYRAK", "Awgust aýynda, tomus bilen güýzüň sepgidinde dogýan ýyldyz", "medium"),
    ("KERWENGYRAN", "Ýupiter planetasy", "medium"),
    ("MYRRYH", "Mars planetasy", "medium"),
    ("BOTANIKA", "ösümlikleri öwrenýän ylym", "medium"),
    ("ALAJAGÖZEN", "Pişikden kiçiräk, ala reňkli, ýakymsyz ysly haýwan", "medium"),
    ("ALAMAN", "ýesir almak, maksady bilen edilýän çozuş", "medium"),
    ("GAPLAŇGYR", "Daşoguz welaýatynda ýerleşýän döwlet goraghanasy", "medium"),
    ("SÜNT-HASARDAG", "Günorta-Günbatar Köpetdagda ýerleşýän tebigy goraghana", "medium"),
    ("BABA GAMMAR", "Ýolöten etrabynda dutaryň piri", "medium"),
    ("TETIS", "gadymyýetde Hazar deňzi bu ummanyň bir bölegidi", "medium"),
    ("DÜWLEN", "Hazar deňzinde ýaşaýan süýdemdiriji haýwan", "medium"),
    ("BENEWŞE", "(älemgoşar) gyzyl, mämişi, sary, ýaşyl, açyk gör, gök, ... (фиолетовый)", "medium"),
    ("LUWR", "Parižiň dünýä belli muzeýi", "medium"),
    ("TEJEN", "Ahal welaýatynyň iň uly şaheri", "medium"),
    ("GARABEKEWÜL", "konýyagy meşhur etrap", "medium"),
    ("DÜWÜNÇEK", "Içine süýji, köke ýaly zatlar salnyp toýpaý berilýärdi..", "medium"),
    ("DÜÝEBOÝUN", "Köýnegiň ýakasyna salynýan nagyş we onuň ady", "medium"),
    ("DYMMA", "köp geplemeýän, geplemsek däl", "medium"),
    ("DYM-DYRSLYK", "ümsümlik", "medium"),
    ("EDÄHET", "endik, gylyk, her bir adamyň boluş aýratynlygy", "medium"),
    ("EGELE", "Mähelle, märeke, üýşmeleň.", "medium"),
    ("GEMRIJI", "Alyn dişleri güýçli ösen syçan, alaka we ş.m. süýdemdiriji haýwan", "medium"),
    ("AZOT", "Howanyň takmynan 80% tutýan himiki element.", "medium"),
    ("GENETIKA", "Organizmleriň döreýişi, üýtgeýişi we nesilden nesle geçiş kanunalaýyklaryny öwrenýän ylym.", "medium"),
    ("GEŇZEW", "Burnuna salyp gürleýän adam.", "medium"),
    ("FATIHA", "\"Pata\" sözüniň düýp sözi", "medium"),
    ("PAÝTUN", "Üsti açylyp ýapylýan, at goşulyp münülýän ýeňil araba.", "medium"),
    ("PAÝAPYL", "Ýabyň üstünden geçmek üçin goýulýan agaç, galyň tagta.", "medium"),
    ("PAÝENDAZ", "Aýak aşagyna düşelýän düşek.", "medium"),
    ("PELÄKET", "Şum, ýaramaz, bezzat.", "medium"),
    ("PERGANAT", "Dikuçaryň, wertolýodyň ýene bir aýdylyşy.", "medium"),
    ("PÜRS", "Gapdaldan çykan pudaklary aýrylyp ýylmanan uzyn agaç.", "medium"),
    ("SOGAP", "Eden ýagşylygyň üçin hudaý tarapyndan özüňe edilýän hormat sylag.", "medium"),
    ("YHSAN", "Ýagşylyk, haýyr iş.", "medium"),
    ("ÝALKASA", "........ ýaz, gargasa gyş! (Atalar sözi)", "medium"),
    ("ÝALÇAMAZ", "Howlugan gyz äre baryp ...... (Nakyl)", "medium"),
    ("ÝAPYNJA", "Ýaz ... ýanyňdan goýma, gyşda halanyňy et (Nakyl).", "medium"),
    ("ÝARGAK", "Etiň daşyndaky perde, ýary.", "medium"),
    ("TÜÝNÜK", "Gara öýüň ýokarky tegelek bölegi.", "medium"),
    ("TÄRIM", "Gara öýüň daýanç merkezi, diwary bolan gözenek agaç enjam.", "medium"),
    ("TÄRET", "Namaza durmazdan öň alynýar.", "medium"),
    ("TIBIT", "Adamyň aşaky dodagynyň çukurja, oýja ýeri.", "medium"),
    ("MICLAB", "Türkmen aýdymlarynyň karaoke priloženiýasy.", "medium"),
    ("IŇŇE", "Ylym almak .... bilen guýy gazmak", "medium"),
    ("KEPGIR", "Palawy agdarmak üçin ulanylýan uzyn saply gural.", "medium"),
    ("HUMAÝUN", "Öňki döwürlerde \"Bagtly\" diýen manyda patyşalara berilýän at.", "medium"),
    ("HUMAÝ", "Gadymy düşünjä görä, kimiň üstüne kölege salsa, şol adam patyşa bolýarmyş diýilýän hyýaly guş.", "medium"),
    ("HATAMTAÝ", "Rowaýatlara görä iň sahy adam.", "medium"),
    ("DISNEYLAND", "Çagalaryň meşhur täsinlikler oýun dünýäsi.", "medium"),
    ("MINECRAFT", "Çagalaryň meşhur internet oýuny.", "medium"),
    ("BAGTYÝARLYK", "Baş şäheriň bir bölegi (etrap).", "medium"),
    ("ÖÝDÜM", "Palas, düýpli gyňaç öýdelende ýerine ýetirilýän bir gezekki tilsim.", "medium"),
    ("ÖZEN", "Agajyň içki gaty bölegi.", "medium"),
    ("RAKYP", "Duşman, keseki, ýat.", "medium"),
    ("RAÝYŞ", "Ýap gazylanda iki tarapa oklanyp çykarylýan gum.", "medium"),
    ("RAKS", "Oýun, tans.", "medium"),
    ("KENDIRIK", "Üstünde un elenýän we hamyr ýugrulýan sanaç.", "medium"),
    ("REPIDE", "Tamdyra çörek ýapmak üçin ele geýilýän tegelek enjam.", "medium"),
    ("GAÝRA", "Demirgazyk-Gündogar aralykdakly tarap.", "medium"),
    ("PELLE", "Deň iki kesilen garpyzyň, gawunyň bir bölegi.", "medium"),
    ("PEREŇ", "Magtymgulynyň goşgularynda Ýewropa, Fransiýa.", "medium"),
    ("PYRKAT", "Aýralyk, aýra düşmeklik. (Magtymguly)", "medium"),
    ("REÝHAN", "Gül ady (bazilik).", "medium"),
    ("FELDŞER", "Orta bilimli medisina işgäri.", "medium"),
    ("FOLKLOR", "Ýatdan aýdylýan halk döredijiligi.", "medium"),
    ("FLAGMAN", "Gämiler we uçarlar toparynyň ýa-da eskadrasynyň serkerdesi.", "medium"),
    ("BABASYL", "Göni içegäniň aşak bölegi käwagt ganap, düwün emele gelýän kesel, gemorroý.", "medium"),
    ("NESÝE", "Söwda-satykda belli bir möhlete çenli pulsuz alnan, nagt bolmadyk.", "medium"),
    ("KAPASA", "Guş saklaýan gözenek-gözenek öýjük.", "medium"),
    ("KAKMAÇ", "Ýukajyk dilnen et.", "medium"),
    ("SELIN", "Gumda bitýän pür ýaprakly köpýyllyk ösümlik.", "medium"),
    ("SEKI", "Üstünde oturmak üçin gumdan, agaçdan edilen belent ýer.", "medium"),
    ("SILINDR", "Porşen ýöreýän turba görnüşindäki abzal.", "medium"),
    ("SÖRTÜK", "Gündogar tarapdan öwüsýän ýakymsyz şemal.", "medium"),
    ("KÄKILIK", "Towuklar maşgalasyndan bolan meýdan guşy.", "medium"),
    ("KÜLÇE", "Tegelek köke, çörek.", "medium"),
    ("GOÝTUK", "Boýy kelte, kiçijik.", "medium"),
    ("GARAGAŞ", "Ýüpek ýaglygyň bir görnüşi.", "medium"),
    ("GARTAŇ", "Garrap başlan, ýaşy bir çene ýeten.", "medium"),
    ("GERMEÇ", "Öýüň gapysynyň aşak çetine germelýän agaç.", "medium"),
    ("GEŇZEWI", "Dutaryň 4-nji perdesi.", "medium"),
    ("PERIŞDE", "Tebigatdan daşary, metafiziki janlylar, melek.", "medium"),
    ("ÖRE", "Öýüň, çatmanyň içinden urulýan sütün.", "medium"),
    ("ŞYTYRDY", "Odun-çöp, agaç ýuwaşlyk bilen döwlende.", "medium"),
    ("ÝERDÖLE", "Galapyn mal saklamak we gyşlatmak üçin ýerden gazylyp, üsti basyrylýan jaý.", "medium"),
    ("ÇALPAW", "Suw ýygnanyp, batga bolup ýatan ýer.", "medium"),
    ("ÇERRIK", "Çölde bitýän zäherli ot.", "medium"),
    ("RITORIKA", "Gepe çeperlik täri, dilewarlyk.", "medium"),
    ("ROUTER", "Öýde internet paýlaýan desga.", "medium"),
    ("EMOJI", "Telefonda we başga ýerlerde harp ýerine ulanylýan suratjyklar.", "medium"),
    ("ALGORITM", "Sosýal platformalarda näme görkezmelidigini hasaplaýan sistema.", "medium"),
    ("CHATGPT", "Meşhur emeli aňly platforma.", "medium"),
    ("SAÝAWAN", "Zontik.", "medium"),
    ("OWŞANAKLAMAK", "Aýaklaryň arasyny giň açyp ýöremek.", "medium"),
    ("ÝEGDÄNE", "Bir däneli ýokary sort ak üzüm", "medium"),
    ("IKINDI", "Gün ýaşmazynyň öňüsyrasy.", "medium"),
    ("GÜRZI", "Demir ýenjilýän ullakan agyr çekiç.", "medium"),
    ("ANDROID", "Samsung, Xiaomi enjamlarynyň operasiýon sistemasy.", "medium"),
    ("HARMONYOS", "Huawei enjamlarynyň operasion sistemasy.", "medium"),
    ("ÝANGY GALA", "Balkan welaýatynda kanýon.", "medium"),
    ("AKMAÝANYŇ", "...... Ýoly içinde Gün ulgamy ýerleşýän galaktikadyr", "medium"),
    ("SMELÝANSKAÝA", "Aýnanyň rolyny oýnan aktrisa Žanna ... .", "medium"),
    ("GERKEZ", "Pyragynyň doglan ýeri, obasy.", "medium"),
    ("RAGBAT", "Hereket edip bilmäge mümkinçilik berýän ysgyn, güýç, kuwwat.", "medium"),
    ("RIŞBENT", "Goraýjy geýim.", "medium"),
    ("ROMANS", "Gahrymanyň içki duýgularyny beýan edýän kiçiräk aýdym.", "medium"),
    ("SAGANA", "Içi otag ýaly, kerpiçden örülen mazar gümmezi.", "medium"),
    ("BALAHANA", "50-60 ýyl mundan öň çagalara bakylýan kiçijik tam.", "medium"),
    ("PYTHON", "Kodlama dili, programmasy", "medium"),
    ("KRUASSAN", "Ýarymaý şekilli hamyr önümi.", "medium"),
    ("ZEMISTAN", "Gyş", "medium"),
    ("ZAGARA", "Jöwen ýa-da mekge unundan bişirilýän kiçiräk tegelek çörek", "medium"),
    ("ZAKGUN", "Dowzahda ösýän, miwesi zäherli agaç.", "medium"),
    ("ÝYMSARMAK", "Ýerliksiz çekinjeňlik, utanjaňlyk sebäpli diýjegiňi diýip bilmezlik.", "medium"),
    ("TELESKOP", "Asman jisimlerine gözegçilik etmek üçin abzal.", "medium"),
    ("TELBE", "Akylyndan azaşan, däli.", "medium"),
    ("TARAKGA", "Gürpüldisi bilen duşmany gorkuzmak üçin, diňe däri doldurylan oksuz, pagtabent ýarag.", "medium"),
    ("TAPMAÇA", "Çylşyrymly oýun, kim bilmeşek.", "medium"),
    ("TAPBAT", "Eliň aýa tarapy, eliň iç ýüzi.", "medium"),
    ("ARHEOLOGIÝA", "Adamzat jemgyýetiniň taryhy geçmişini gazuw-agtaryş işleriniň netijesinde öwrenýän ylym", "medium"),
    ("ARHIPELAG", "Köp sanly adalaryň jemi ýa-da olaryň topary", "medium"),
    ("DIKDÜŞDI", "Öz diýenini etdirjek bolup dyrjaşýan, düşünmezek.", "medium"),
    ("DIKEÇ", "Dürtgüç.", "medium"),
    ("DIKAN", "Göni, dogry.", "medium"),
    ("DIKANA", "Käriziň dik çukury.", "medium"),
    ("IPOTEKA", "Ýaşaýyş jaý satyn almak üçin bankdan alynýan karz", "medium"),
    ("ÝARTYGULAK", "Keltejik boýly gahryman", "medium"),
    ("MOLLANEPES", "Gözel duýgulary, ajaýyp arzuwlary oýarýan liriki şahyr", "medium"),
    ("ÄHTIMALLYK", "Eýnşteýniň meşhur _ _ _ _ _ _ _ _ teoriýasy", "medium"),
    ("STETOSKOP", "Içki organlar diňlenende hem-de gan basyşy ölçelende ulanylýan abzal", "medium"),
    ("BAROMETR", "Howanyň basyşyny ölçeýän abzal.", "medium"),
    ("BAŞAGAÝ", "aljyraňňy; iş alada bilen ýetişiksiz;", "medium"),
    ("BAŞAM", "Eliň, aýagyň ilkinji ýogyn barmagy.", "medium"),
    ("BAŞARJAŇ", "Işe ukyply.", "medium"),
    ("BAŞDAŞ", "Erkek adamyň ilki öýlenen aýaly ýa-da aýalyň ilki durmuşa çykan adamsy.", "medium"),
    ("BAŞGAP", "Kellä geýilýän zatlaryň umumy ady.", "medium"),
    ("ARMSTRONG", "Aýa ilkinji aýak basan adam: Neýl ...", "medium"),
    ("BATGA", "Ýagyn ýagyp ýa-da suw basyp, emele gelen lüýk ýer.", "medium"),
    ("BATYL", "Görmekden mahrum, kör.", "medium"),
    ("BATNYK", "Edilýän hereketiň, aýdylýan sözüň ýerlikliligi; ýakym.", "medium"),
    ("BATRAK", "Öňki döwürlerde hojalykda işleýän hakyna tutulan daýhan.", "medium"),
    ("BAWAR", "Magtymgulynyň goşgularynda: Ynam, Ynanç, Ynanyş.", "medium"),
    ("BAÝTAL", "Ene ýaby", "medium"),
    ("BAZ", "Köne türkmen dilinde: Laçyn, Elguş", "medium"),
    ("BAÝZY", "Toklulardan ilkinji gezek gyrkylyp alynýan ýüň.", "medium"),
    ("BEDE", "Mal iými üçin orlup guradylyp goýlan ot.", "medium"),
    ("PÜRDEMEK", "Agajyň gapdal ownuk pudaklaryny çapyp, kesip aýyrmak", "medium"),
    ("PYNHAN", "Ogryn, gizlin, ýaşyryn; hiç kime duýdurman.", "medium"),
    ("ÜME", "Durmuşa çykjak gyzyň eşiklerini tikmek üçin gyz gelinleriň ýowar şekilli ýygnanyşygy.", "medium"),
    ("ÜDEK", "Içine örüm edilmedik guýy.", "medium"),
    ("POTTER", "Hogwarts'da okaýam Garrinyň familiýasy.", "medium"),
    ("GAGARIN", "Kosmosda dünýäniň daşyndan aýlanan ilknji adamyň familiýasy.", "medium"),
    ("TEREŞKOWA", "Kosmosa çykan ilknji aýal kosmonawt. Familiýasy.", "medium"),
    ("ALPHABET", "Google platformasynyň arkasyndaky kopmaniýa.", "medium"),
    ("HURUŞ", "Çörek bilen iýmek üçin gerekli iýmit.", "medium"),
    ("HYNA", "Saça, sakgala we ş.m. çalynýan boýag.", "medium"),
    ("HYLLALLALY", "Kynçylykly amala aşyrylýan, görgüsi köp bolan.", "medium"),
    ("HYKARAT", "Kemsitme", "medium"),
    ("HYJYL", "Utanç, utanç-haýa.", "medium"),
    ("HYJUW", "Işe, okuwa we ş.m. herekete bolan güýçli joşgun, isleg.", "medium"),
    ("HÜÝDEŞ", "Gylykdaş, häsiýetdeş, pikirdeş.", "medium"),
]


def seed_words(apps, schema_editor):
    HangmanWord = apps.get_model('hangman', 'HangmanWord')
    seen = set()
    for word, hint, difficulty in WORDS:
        if word in seen:
            continue
        seen.add(word)
        HangmanWord.objects.get_or_create(
            word=word,
            defaults={'hint': hint, 'difficulty': difficulty, 'is_active': True},
        )


def unseed_words(apps, schema_editor):
    pass  # intentionally a no-op — don't delete words on rollback


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0003_chat'),
    ]

    operations = [
        migrations.RunPython(seed_words, reverse_code=unseed_words),
    ]
